name: Deploy to GitHub Pages

on:
  push:
    branches: [master] # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Set your desired pnpm version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # or your Node version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build' # SvelteKit's default output for static adapter

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

